// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="block_fir_block_fir,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010-clg225-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.210000,HLS_SYN_LAT=10497,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1716,HLS_SYN_LUT=854,HLS_VERSION=2025_1}" *)

module block_fir (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        taps_0,
        taps_1,
        taps_2,
        taps_3,
        taps_4,
        taps_5,
        taps_6,
        taps_7,
        taps_8,
        taps_9,
        taps_10,
        taps_11,
        taps_12,
        taps_13,
        taps_14,
        taps_15,
        delay_line_0_i,
        delay_line_0_o,
        delay_line_0_o_ap_vld,
        delay_line_1_i,
        delay_line_1_o,
        delay_line_1_o_ap_vld,
        delay_line_2_i,
        delay_line_2_o,
        delay_line_2_o_ap_vld,
        delay_line_3_i,
        delay_line_3_o,
        delay_line_3_o_ap_vld,
        delay_line_4_i,
        delay_line_4_o,
        delay_line_4_o_ap_vld,
        delay_line_5_i,
        delay_line_5_o,
        delay_line_5_o_ap_vld,
        delay_line_6_i,
        delay_line_6_o,
        delay_line_6_o_ap_vld,
        delay_line_7_i,
        delay_line_7_o,
        delay_line_7_o_ap_vld,
        delay_line_8_i,
        delay_line_8_o,
        delay_line_8_o_ap_vld,
        delay_line_9_i,
        delay_line_9_o,
        delay_line_9_o_ap_vld,
        delay_line_10_i,
        delay_line_10_o,
        delay_line_10_o_ap_vld,
        delay_line_11_i,
        delay_line_11_o,
        delay_line_11_o_ap_vld,
        delay_line_12_i,
        delay_line_12_o,
        delay_line_12_o_ap_vld,
        delay_line_13_i,
        delay_line_13_o,
        delay_line_13_o_ap_vld,
        delay_line_14_i,
        delay_line_14_o,
        delay_line_14_o_ap_vld,
        delay_line_15_i,
        delay_line_15_o,
        delay_line_15_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [7:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
input  [31:0] taps_0;
input  [31:0] taps_1;
input  [31:0] taps_2;
input  [31:0] taps_3;
input  [31:0] taps_4;
input  [31:0] taps_5;
input  [31:0] taps_6;
input  [31:0] taps_7;
input  [31:0] taps_8;
input  [31:0] taps_9;
input  [31:0] taps_10;
input  [31:0] taps_11;
input  [31:0] taps_12;
input  [31:0] taps_13;
input  [31:0] taps_14;
input  [31:0] taps_15;
input  [31:0] delay_line_0_i;
output  [31:0] delay_line_0_o;
output   delay_line_0_o_ap_vld;
input  [31:0] delay_line_1_i;
output  [31:0] delay_line_1_o;
output   delay_line_1_o_ap_vld;
input  [31:0] delay_line_2_i;
output  [31:0] delay_line_2_o;
output   delay_line_2_o_ap_vld;
input  [31:0] delay_line_3_i;
output  [31:0] delay_line_3_o;
output   delay_line_3_o_ap_vld;
input  [31:0] delay_line_4_i;
output  [31:0] delay_line_4_o;
output   delay_line_4_o_ap_vld;
input  [31:0] delay_line_5_i;
output  [31:0] delay_line_5_o;
output   delay_line_5_o_ap_vld;
input  [31:0] delay_line_6_i;
output  [31:0] delay_line_6_o;
output   delay_line_6_o_ap_vld;
input  [31:0] delay_line_7_i;
output  [31:0] delay_line_7_o;
output   delay_line_7_o_ap_vld;
input  [31:0] delay_line_8_i;
output  [31:0] delay_line_8_o;
output   delay_line_8_o_ap_vld;
input  [31:0] delay_line_9_i;
output  [31:0] delay_line_9_o;
output   delay_line_9_o_ap_vld;
input  [31:0] delay_line_10_i;
output  [31:0] delay_line_10_o;
output   delay_line_10_o_ap_vld;
input  [31:0] delay_line_11_i;
output  [31:0] delay_line_11_o;
output   delay_line_11_o_ap_vld;
input  [31:0] delay_line_12_i;
output  [31:0] delay_line_12_o;
output   delay_line_12_o_ap_vld;
input  [31:0] delay_line_13_i;
output  [31:0] delay_line_13_o;
output   delay_line_13_o_ap_vld;
input  [31:0] delay_line_14_i;
output  [31:0] delay_line_14_o;
output   delay_line_14_o_ap_vld;
input  [31:0] delay_line_15_i;
output  [31:0] delay_line_15_o;
output   delay_line_15_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] delay_line_0_o;
reg delay_line_0_o_ap_vld;
reg[31:0] delay_line_1_o;
reg delay_line_1_o_ap_vld;
reg[31:0] delay_line_2_o;
reg delay_line_2_o_ap_vld;
reg[31:0] delay_line_3_o;
reg delay_line_3_o_ap_vld;
reg[31:0] delay_line_4_o;
reg delay_line_4_o_ap_vld;
reg[31:0] delay_line_5_o;
reg delay_line_5_o_ap_vld;
reg[31:0] delay_line_6_o;
reg delay_line_6_o_ap_vld;
reg[31:0] delay_line_7_o;
reg delay_line_7_o_ap_vld;
reg[31:0] delay_line_8_o;
reg delay_line_8_o_ap_vld;
reg[31:0] delay_line_9_o;
reg delay_line_9_o_ap_vld;
reg[31:0] delay_line_10_o;
reg delay_line_10_o_ap_vld;
reg[31:0] delay_line_11_o;
reg delay_line_11_o_ap_vld;
reg[31:0] delay_line_12_o;
reg delay_line_12_o_ap_vld;
reg[31:0] delay_line_13_o;
reg delay_line_13_o_ap_vld;
reg[31:0] delay_line_14_o;
reg delay_line_14_o_ap_vld;
reg[31:0] delay_line_15_o;
reg delay_line_15_o_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] taps_0_read_reg_483;
reg   [31:0] taps_1_read_reg_488;
reg   [31:0] taps_2_read_reg_493;
reg   [31:0] taps_3_read_reg_498;
reg   [31:0] taps_4_read_reg_503;
reg   [31:0] taps_5_read_reg_508;
reg   [31:0] taps_6_read_reg_513;
reg   [31:0] taps_7_read_reg_518;
reg   [31:0] taps_8_read_reg_523;
reg   [31:0] taps_9_read_reg_528;
reg   [31:0] taps_10_read_reg_533;
reg   [31:0] taps_11_read_reg_538;
reg   [31:0] taps_12_read_reg_543;
reg   [31:0] taps_13_read_reg_548;
reg   [31:0] taps_14_read_reg_553;
reg   [31:0] taps_15_read_reg_558;
reg   [8:0] j_1_reg_563;
wire    ap_CS_fsm_state2;
reg   [31:0] delay_line_0_read_reg_571;
wire   [63:0] zext_ln10_fu_462_p1;
reg   [63:0] zext_ln10_reg_576;
wire    ap_CS_fsm_state3;
reg   [31:0] input_r_load_reg_586;
wire    ap_CS_fsm_state4;
reg   [31:0] delay_line_1_read_reg_591;
reg   [31:0] delay_line_2_read_reg_596;
reg   [31:0] delay_line_3_read_reg_601;
reg   [31:0] delay_line_4_read_reg_606;
reg   [31:0] delay_line_5_read_reg_611;
reg   [31:0] delay_line_6_read_reg_616;
reg   [31:0] delay_line_7_read_reg_621;
reg   [31:0] delay_line_8_read_reg_626;
reg   [31:0] delay_line_9_read_reg_631;
reg   [31:0] delay_line_10_read_reg_636;
reg   [31:0] delay_line_11_read_reg_641;
reg   [31:0] delay_line_12_read_reg_646;
reg   [31:0] delay_line_13_read_reg_651;
reg   [31:0] delay_line_14_read_reg_656;
reg   [31:0] delay_line_15_read_reg_661;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_done;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_idle;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_ready;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o_ap_vld;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o;
wire    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o_ap_vld;
wire    grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start;
wire    grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_done;
wire    grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_idle;
wire    grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_ready;
wire   [31:0] grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_result_out;
wire    grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_result_out_ap_vld;
reg    grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start_reg;
wire   [0:0] icmp_ln10_fu_445_p2;
reg   [31:0] delay_line_1_o_reg;
reg   [31:0] delay_line_15_o_reg;
reg   [31:0] delay_line_14_o_reg;
reg   [31:0] delay_line_13_o_reg;
reg   [31:0] delay_line_12_o_reg;
reg   [31:0] delay_line_11_o_reg;
reg   [31:0] delay_line_10_o_reg;
reg   [31:0] delay_line_9_o_reg;
reg   [31:0] delay_line_8_o_reg;
reg   [31:0] delay_line_7_o_reg;
reg   [31:0] delay_line_6_o_reg;
reg   [31:0] delay_line_5_o_reg;
reg   [31:0] delay_line_4_o_reg;
reg   [31:0] delay_line_3_o_reg;
reg   [31:0] delay_line_2_o_reg;
reg    grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [8:0] j_fu_114;
wire   [8:0] add_ln10_fu_451_p2;
reg    input_r_ce0_local;
reg    output_r_we0_local;
reg    output_r_ce0_local;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start_reg = 1'b0;
#0 grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start_reg = 1'b0;
#0 j_fu_114 = 9'd0;
end

block_fir_block_fir_Pipeline_VITIS_LOOP_12_2 grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start),
    .ap_done(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_done),
    .ap_idle(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_idle),
    .ap_ready(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_ready),
    .delay_line_1_i(delay_line_1_i),
    .delay_line_1_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o),
    .delay_line_1_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o_ap_vld),
    .delay_line_15(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15),
    .delay_line_15_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15_ap_vld),
    .delay_line_14_i(delay_line_14_i),
    .delay_line_14_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o),
    .delay_line_14_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o_ap_vld),
    .delay_line_13_i(delay_line_13_i),
    .delay_line_13_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o),
    .delay_line_13_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o_ap_vld),
    .delay_line_12_i(delay_line_12_i),
    .delay_line_12_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o),
    .delay_line_12_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o_ap_vld),
    .delay_line_11_i(delay_line_11_i),
    .delay_line_11_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o),
    .delay_line_11_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o_ap_vld),
    .delay_line_10_i(delay_line_10_i),
    .delay_line_10_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o),
    .delay_line_10_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o_ap_vld),
    .delay_line_9_i(delay_line_9_i),
    .delay_line_9_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o),
    .delay_line_9_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o_ap_vld),
    .delay_line_8_i(delay_line_8_i),
    .delay_line_8_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o),
    .delay_line_8_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o_ap_vld),
    .delay_line_7_i(delay_line_7_i),
    .delay_line_7_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o),
    .delay_line_7_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o_ap_vld),
    .delay_line_6_i(delay_line_6_i),
    .delay_line_6_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o),
    .delay_line_6_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o_ap_vld),
    .delay_line_5_i(delay_line_5_i),
    .delay_line_5_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o),
    .delay_line_5_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o_ap_vld),
    .delay_line_4_i(delay_line_4_i),
    .delay_line_4_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o),
    .delay_line_4_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o_ap_vld),
    .delay_line_3_i(delay_line_3_i),
    .delay_line_3_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o),
    .delay_line_3_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o_ap_vld),
    .delay_line_2_i(delay_line_2_i),
    .delay_line_2_o(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o),
    .delay_line_2_o_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o_ap_vld),
    .delay_line_0_load(delay_line_0_read_reg_571)
);

block_fir_block_fir_Pipeline_VITIS_LOOP_19_3 grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start),
    .ap_done(grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_done),
    .ap_idle(grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_idle),
    .ap_ready(grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_ready),
    .input_r_load(input_r_load_reg_586),
    .delay_line_1_load_1(delay_line_1_read_reg_591),
    .delay_line_2_load_1(delay_line_2_read_reg_596),
    .delay_line_3_load_1(delay_line_3_read_reg_601),
    .delay_line_4_load_1(delay_line_4_read_reg_606),
    .delay_line_5_load_1(delay_line_5_read_reg_611),
    .delay_line_6_load_1(delay_line_6_read_reg_616),
    .delay_line_7_load_1(delay_line_7_read_reg_621),
    .delay_line_8_load_1(delay_line_8_read_reg_626),
    .delay_line_9_load_1(delay_line_9_read_reg_631),
    .delay_line_10_load_1(delay_line_10_read_reg_636),
    .delay_line_11_load_1(delay_line_11_read_reg_641),
    .delay_line_12_load_1(delay_line_12_read_reg_646),
    .delay_line_13_load_1(delay_line_13_read_reg_651),
    .delay_line_14_load_1(delay_line_14_read_reg_656),
    .delay_line_15_load(delay_line_15_read_reg_661),
    .taps_0_load(taps_0_read_reg_483),
    .taps_1_load(taps_1_read_reg_488),
    .taps_2_load(taps_2_read_reg_493),
    .taps_3_load(taps_3_read_reg_498),
    .taps_4_load(taps_4_read_reg_503),
    .taps_5_load(taps_5_read_reg_508),
    .taps_6_load(taps_6_read_reg_513),
    .taps_7_load(taps_7_read_reg_518),
    .taps_8_load(taps_8_read_reg_523),
    .taps_9_load(taps_9_read_reg_528),
    .taps_10_load(taps_10_read_reg_533),
    .taps_11_load(taps_11_read_reg_538),
    .taps_12_load(taps_12_read_reg_543),
    .taps_13_load(taps_13_read_reg_548),
    .taps_14_load(taps_14_read_reg_553),
    .taps_15_load(taps_15_read_reg_558),
    .result_out(grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_result_out),
    .result_out_ap_vld(grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_result_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln10_fu_445_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start_reg <= 1'b1;
        end else if ((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_ready == 1'b1)) begin
            grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start_reg <= 1'b1;
        end else if ((grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_ready == 1'b1)) begin
            grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_fu_114 <= 9'd0;
    end else if (((icmp_ln10_fu_445_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_fu_114 <= add_ln10_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        delay_line_0_read_reg_571 <= delay_line_0_i;
        j_1_reg_563 <= j_fu_114;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_10_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        delay_line_10_read_reg_636 <= delay_line_10_i;
        delay_line_11_read_reg_641 <= delay_line_11_i;
        delay_line_12_read_reg_646 <= delay_line_12_i;
        delay_line_13_read_reg_651 <= delay_line_13_i;
        delay_line_14_read_reg_656 <= delay_line_14_i;
        delay_line_15_read_reg_661 <= delay_line_15_i;
        delay_line_1_read_reg_591 <= delay_line_1_i;
        delay_line_2_read_reg_596 <= delay_line_2_i;
        delay_line_3_read_reg_601 <= delay_line_3_i;
        delay_line_4_read_reg_606 <= delay_line_4_i;
        delay_line_5_read_reg_611 <= delay_line_5_i;
        delay_line_6_read_reg_616 <= delay_line_6_i;
        delay_line_7_read_reg_621 <= delay_line_7_i;
        delay_line_8_read_reg_626 <= delay_line_8_i;
        delay_line_9_read_reg_631 <= delay_line_9_i;
        input_r_load_reg_586 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_11_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_12_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_13_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_14_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_15_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o_ap_vld == 1'b1))) begin
        delay_line_1_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_2_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_3_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_4_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_5_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_6_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_7_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_8_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_9_o_reg <= grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        taps_0_read_reg_483 <= taps_0;
        taps_10_read_reg_533 <= taps_10;
        taps_11_read_reg_538 <= taps_11;
        taps_12_read_reg_543 <= taps_12;
        taps_13_read_reg_548 <= taps_13;
        taps_14_read_reg_553 <= taps_14;
        taps_15_read_reg_558 <= taps_15;
        taps_1_read_reg_488 <= taps_1;
        taps_2_read_reg_493 <= taps_2;
        taps_3_read_reg_498 <= taps_3;
        taps_4_read_reg_503 <= taps_4;
        taps_5_read_reg_508 <= taps_5;
        taps_6_read_reg_513 <= taps_6;
        taps_7_read_reg_518 <= taps_7;
        taps_8_read_reg_523 <= taps_8;
        taps_9_read_reg_528 <= taps_9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        zext_ln10_reg_576[8 : 0] <= zext_ln10_fu_462_p1[8 : 0];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln10_fu_445_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln10_fu_445_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        delay_line_0_o = input_r_q0;
    end else begin
        delay_line_0_o = delay_line_0_i;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        delay_line_0_o_ap_vld = 1'b1;
    end else begin
        delay_line_0_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_10_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o;
    end else begin
        delay_line_10_o = delay_line_10_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_10_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_10_o_ap_vld;
    end else begin
        delay_line_10_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_11_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o;
    end else begin
        delay_line_11_o = delay_line_11_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_11_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_11_o_ap_vld;
    end else begin
        delay_line_11_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_12_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o;
    end else begin
        delay_line_12_o = delay_line_12_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_12_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_12_o_ap_vld;
    end else begin
        delay_line_12_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_13_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o;
    end else begin
        delay_line_13_o = delay_line_13_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_13_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_13_o_ap_vld;
    end else begin
        delay_line_13_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_14_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o;
    end else begin
        delay_line_14_o = delay_line_14_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_14_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_14_o_ap_vld;
    end else begin
        delay_line_14_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_15_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15;
    end else begin
        delay_line_15_o = delay_line_15_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_15_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_15_ap_vld;
    end else begin
        delay_line_15_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o_ap_vld == 1'b1))) begin
        delay_line_1_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o;
    end else begin
        delay_line_1_o = delay_line_1_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_1_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_1_o_ap_vld;
    end else begin
        delay_line_1_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_2_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o;
    end else begin
        delay_line_2_o = delay_line_2_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_2_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_2_o_ap_vld;
    end else begin
        delay_line_2_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_3_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o;
    end else begin
        delay_line_3_o = delay_line_3_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_3_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_3_o_ap_vld;
    end else begin
        delay_line_3_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_4_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o;
    end else begin
        delay_line_4_o = delay_line_4_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_4_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_4_o_ap_vld;
    end else begin
        delay_line_4_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_5_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o;
    end else begin
        delay_line_5_o = delay_line_5_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_5_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_5_o_ap_vld;
    end else begin
        delay_line_5_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_6_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o;
    end else begin
        delay_line_6_o = delay_line_6_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_6_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_6_o_ap_vld;
    end else begin
        delay_line_6_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_7_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o;
    end else begin
        delay_line_7_o = delay_line_7_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_7_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_7_o_ap_vld;
    end else begin
        delay_line_7_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_8_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o;
    end else begin
        delay_line_8_o = delay_line_8_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_8_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_8_o_ap_vld;
    end else begin
        delay_line_8_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        delay_line_9_o = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o;
    end else begin
        delay_line_9_o = delay_line_9_o_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        delay_line_9_o_ap_vld = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_delay_line_9_o_ap_vld;
    end else begin
        delay_line_9_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_done == 1'b1))) begin
        input_r_ce0_local = 1'b1;
    end else begin
        input_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_r_ce0_local = 1'b1;
    end else begin
        output_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        output_r_we0_local = 1'b1;
    end else begin
        output_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln10_fu_445_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln10_fu_451_p2 = (j_fu_114 + 9'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start = grp_block_fir_Pipeline_VITIS_LOOP_12_2_fu_348_ap_start_reg;

assign grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start = grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_ap_start_reg;

assign icmp_ln10_fu_445_p2 = ((j_fu_114 == 9'd256) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln10_fu_462_p1;

assign input_r_ce0 = input_r_ce0_local;

assign output_r_address0 = zext_ln10_reg_576;

assign output_r_ce0 = output_r_ce0_local;

assign output_r_d0 = grp_block_fir_Pipeline_VITIS_LOOP_19_3_fu_384_result_out;

assign output_r_we0 = output_r_we0_local;

assign zext_ln10_fu_462_p1 = j_1_reg_563;

always @ (posedge ap_clk) begin
    zext_ln10_reg_576[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //block_fir
